import { SystemRole, UserStatus, ScopeType, type User } from '@/modules/shared/types/auth'

export function createMockAdminMaster(email: string): User {
  const now = new Date().toISOString()

  return {
    id: '1',
    name: 'Admin Master',
    email,
    role: SystemRole.ADMIN_MASTER,
    status: UserStatus.ACTIVE,
    scope: { type: ScopeType.GLOBAL },
    permissions: {
      canAccessDashboard: true,
      canViewLive: true,
      canViewRecordings: true,
      canViewPlayback: true,
      canExportVideos: true,
      canExportReports: true,
      canManageUsers: true,
      canManageAdmins: true,
      canManageTechnicians: true,
      canResetPasswords: true,
      canSuspendUsers: true,
      canViewAllTenants: true,
      canManageTenants: true,
      canChangeTenantPlan: true,
      canSuspendTenants: true,
      canManageCameras: true,
      canConfigureStreamProfiles: true,
      canDeleteCameras: true,
      canConfigureAI: true,
      canConfigureAIZones: true,
      canConfigureAISensitivity: true,
      canConfigureRecording: true,
      canDeleteRecordings: true,
      canConfigureAlerts: true,
      canAcknowledgeAlerts: true,
      canManageInfrastructure: true,
      canAccessGlobalAudit: true,
      canManageGlobalSettings: true,
      canForceLogout: true,
      canGrantTemporaryAccess: true,
      canAccessDiagnostics: true,
      canViewLogs: true,
      maxStreamQuality: '4K',
      allowedAIModules: [],
    },
    createdAt: now,
    updatedAt: now,
    lastLogin: undefined,
    avatar: undefined,
    tenantId: undefined,
    tenantName: undefined,
    phone: undefined,
  }
}
